from enum import Enum


class ErrorCode(str, Enum):
    # Auth
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED"
    AUTH_FORBIDDEN = "AUTH_FORBIDDEN"

    # Validation
    VALIDATION_INVALID_FORMAT = "VALIDATION_INVALID_FORMAT"
    VALIDATION_REQUIRED_FIELD = "VALIDATION_REQUIRED_FIELD"

    # User
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    # Course
    COURSE_NOT_FOUND = "COURSE_NOT_FOUND"
    COURSE_ALREADY_JOINED = "COURSE_ALREADY_JOINED"
    COURSE_ARCHIVED = "COURSE_ARCHIVED"
    COURSE_NOT_MEMBER = "COURSE_NOT_MEMBER"
    NICKNAME_REQUIRED = "NICKNAME_REQUIRED"

    # Problem
    PROBLEM_NOT_FOUND = "PROBLEM_NOT_FOUND"
    PROBLEM_LANG_NOT_SUPPORTED = "PROBLEM_LANG_NOT_SUPPORTED"

    # Assignment
    ASSIGNMENT_NOT_FOUND = "ASSIGNMENT_NOT_FOUND"
    ASSIGNMENT_NOT_STARTED = "ASSIGNMENT_NOT_STARTED"
    ASSIGNMENT_EXPIRED = "ASSIGNMENT_EXPIRED"

    # Submission
    SUBMISSION_NOT_FOUND = "SUBMISSION_NOT_FOUND"
    SUBMISSION_LIMIT_EXCEEDED = "SUBMISSION_LIMIT_EXCEEDED"

    # Judge
    JUDGE_COMPILATION_ERROR = "JUDGE_COMPILATION_ERROR"
    JUDGE_RUNTIME_ERROR = "JUDGE_RUNTIME_ERROR"
    JUDGE_TIMEOUT = "JUDGE_TIMEOUT"
    JUDGE_SERVICE_UNAVAILABLE = "JUDGE_SERVICE_UNAVAILABLE"

    # System
    INTERNAL_ERROR = "INTERNAL_ERROR"
